/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.diskchop.view;

import com.diskchop.model.entity.Regime;
import com.diskchop.model.entity.Tipo;

import javax.swing.*;
import java.awt.*;

public class CadastroClientes extends javax.swing.JDialog {

    /**
     * Creates new form CadastroClientes
     */
    public CadastroClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        painelTop = new javax.swing.JPanel();
        labelCadTitulo = new javax.swing.JLabel();
        botaoCadVoltar = new javax.swing.JButton();
        painelCenter = new javax.swing.JPanel();
        labelCadLogradouro = new javax.swing.JLabel();
        textFieldCadLogradouro = new javax.swing.JTextField();
        labelCadNumero = new javax.swing.JLabel();
        textFieldCadNumero = new javax.swing.JTextField();
        textFieldCadCpf = new javax.swing.JTextField();
        labelCadBairro = new javax.swing.JLabel();
        textFieldCadBairro = new javax.swing.JTextField();
        labelCadCidade = new javax.swing.JLabel();
        textFieldCadCidade = new javax.swing.JTextField();
        labelCadUf = new javax.swing.JLabel();
        labelCadCep = new javax.swing.JLabel();
        labelCadNome = new javax.swing.JLabel();
        textFieldCadNome = new javax.swing.JTextField();
        labelCadCpf = new javax.swing.JLabel();
        textFieldCadCep = new javax.swing.JTextField();
        labelCadId = new javax.swing.JLabel();
        textFieldCadId = new javax.swing.JTextField();
        textFieldCadUf = new javax.swing.JTextField();
        labelCadComplemento = new javax.swing.JLabel();
        textFieldCadComplemento = new javax.swing.JTextField();
        labelCadTipo = new javax.swing.JLabel();
        comboCadTipo = new javax.swing.JComboBox<>();
        labelCadObservacaoEndereco = new javax.swing.JLabel();
        textFieldCadObservacaoEndereco = new javax.swing.JTextField();
        comboCadPessoa = new javax.swing.JComboBox<>();
        labelCadPessoa = new javax.swing.JLabel();
        labelCadTelefone = new javax.swing.JLabel();
        textFieldCadTelefone = new javax.swing.JTextField();
        labelCadContato = new javax.swing.JLabel();
        textFieldCadContato = new javax.swing.JTextField();
        labelCadObservacaoCliente = new javax.swing.JLabel();
        textFieldCadObservacaoCliente = new javax.swing.JTextField();
        botaoCadLimpar = new javax.swing.JButton();
        painelBottom = new javax.swing.JPanel();
        tabbedPaneCad = new javax.swing.JTabbedPane();
        painelCadClientes = new javax.swing.JPanel();
        scrollPaneCadClientes = new javax.swing.JScrollPane();
        tableCadClientes = new javax.swing.JTable();
        botaoCadClienteProcurar = new javax.swing.JToggleButton();
        botaoCadClienteDelete = new javax.swing.JButton();
        botaoCadClienteAdicionar = new javax.swing.JButton();
        botaoCadClienteSalvar = new javax.swing.JButton();
        painelCadEnderecos = new javax.swing.JPanel();
        scrollPaneCadEnderecos = new javax.swing.JScrollPane();
        tableCadEnderecos = new javax.swing.JTable();
        botaoCadEnderecoAdicionar = new javax.swing.JToggleButton();
        botaoCadEnderecoDelete = new javax.swing.JToggleButton();
        botaoCadEnderecoProcurar = new javax.swing.JButton();
        botaoCadEnderecoEditar = new javax.swing.JButton();
        painelCadTelefones = new javax.swing.JPanel();
        scrollPaneCadTelefones = new javax.swing.JScrollPane();
        tableCadTelefones = new javax.swing.JTable();
        botaoCadTelefoneAdicionar = new javax.swing.JButton();
        botaoCadTelefoneDelete = new javax.swing.JButton();
        botaoCadTelefoneProcurar = new javax.swing.JButton();
        botaoCadTelefoneEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 77, 64));
        setModal(true);
        setResizable(false);

        painelTop.setBackground(new java.awt.Color(248, 248, 248));
        painelTop.setName("painelTop"); // NOI18N

        labelCadTitulo.setFont(new java.awt.Font("Serif", 1, 40)); // NOI18N
        labelCadTitulo.setForeground(new java.awt.Color(0, 77, 64));
        labelCadTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCadTitulo.setText("Cadastro de Clientes");
        labelCadTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelCadTitulo.setName("labelCadTitulo"); // NOI18N

        botaoCadVoltar.setBackground(new java.awt.Color(250, 250, 250));
        botaoCadVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/voltar.png"))); // NOI18N
        botaoCadVoltar.setToolTipText("Voltar ao Menu Inicial");
        botaoCadVoltar.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        botaoCadVoltar.setBorderPainted(false);
        botaoCadVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelTopLayout = new javax.swing.GroupLayout(painelTop);
        painelTop.setLayout(painelTopLayout);
        painelTopLayout.setHorizontalGroup(
                painelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTopLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(botaoCadVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelCadTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelTopLayout.setVerticalGroup(
                painelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelCadTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelTopLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(botaoCadVoltar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelCenter.setBackground(new java.awt.Color(0, 77, 64));

        labelCadLogradouro.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadLogradouro.setForeground(new java.awt.Color(255, 255, 255));
        labelCadLogradouro.setText("Logradouro:");

        textFieldCadLogradouro.setColumns(40);
        textFieldCadLogradouro.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCadLogradouro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldCadLogradouro.setBorder(null);
        textFieldCadLogradouro.setMargin(new java.awt.Insets(2, 20, 2, 6));
        textFieldCadLogradouro.setPreferredSize(new java.awt.Dimension(50, 22));

        labelCadNumero.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadNumero.setForeground(new java.awt.Color(255, 255, 255));
        labelCadNumero.setText("Nº:");

        textFieldCadNumero.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCadNumero.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldCadNumero.setBorder(null);
        textFieldCadNumero.setMargin(new java.awt.Insets(2, 20, 2, 6));
        textFieldCadNumero.setPreferredSize(new java.awt.Dimension(50, 22));
        textFieldCadNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCadNumeroActionPerformed(evt);
            }
        });

        textFieldCadCpf.setColumns(16);
        textFieldCadCpf.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCadCpf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldCadCpf.setBorder(null);
        textFieldCadCpf.setMargin(new java.awt.Insets(2, 20, 2, 6));
        textFieldCadCpf.setPreferredSize(new java.awt.Dimension(50, 22));

        labelCadBairro.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadBairro.setForeground(new java.awt.Color(255, 255, 255));
        labelCadBairro.setText("Bairro:");

        textFieldCadBairro.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCadBairro.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldCadBairro.setBorder(null);
        textFieldCadBairro.setMargin(new java.awt.Insets(2, 20, 2, 6));
        textFieldCadBairro.setPreferredSize(new java.awt.Dimension(50, 22));
        textFieldCadBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCadBairroActionPerformed(evt);
            }
        });

        labelCadCidade.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadCidade.setForeground(new java.awt.Color(255, 255, 255));
        labelCadCidade.setText("Cidade:");

        textFieldCadCidade.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCadCidade.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldCadCidade.setBorder(null);
        textFieldCadCidade.setMargin(new java.awt.Insets(2, 20, 2, 6));
        textFieldCadCidade.setPreferredSize(new java.awt.Dimension(50, 22));
        textFieldCadCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCadCidadeActionPerformed(evt);
            }
        });

        labelCadUf.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadUf.setForeground(new java.awt.Color(255, 255, 255));
        labelCadUf.setText("UF:");

        labelCadCep.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadCep.setForeground(new java.awt.Color(255, 255, 255));
        labelCadCep.setText("CEP:");

        labelCadNome.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadNome.setForeground(new java.awt.Color(255, 255, 255));
        labelCadNome.setText("Nome:");

        textFieldCadNome.setColumns(40);
        textFieldCadNome.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCadNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldCadNome.setBorder(null);
        textFieldCadNome.setMargin(new java.awt.Insets(2, 12, 2, 6));
        textFieldCadNome.setPreferredSize(new java.awt.Dimension(50, 22));
        textFieldCadNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCadNomeActionPerformed(evt);
            }
        });

        labelCadCpf.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadCpf.setForeground(new java.awt.Color(255, 255, 255));
        labelCadCpf.setText("CPF/CNPJ:");

        textFieldCadCep.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCadCep.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldCadCep.setBorder(null);
        textFieldCadCep.setMargin(new java.awt.Insets(2, 20, 2, 6));
        textFieldCadCep.setPreferredSize(new java.awt.Dimension(50, 22));

        labelCadId.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadId.setForeground(new java.awt.Color(255, 255, 255));
        labelCadId.setText("ID:");

        textFieldCadId.setColumns(5);
        textFieldCadId.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCadId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldCadId.setBorder(null);
        textFieldCadId.setMargin(new java.awt.Insets(2, 12, 2, 6));
        textFieldCadId.setPreferredSize(new java.awt.Dimension(50, 22));
        textFieldCadId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCadIdActionPerformed(evt);
            }
        });

        textFieldCadUf.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCadUf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldCadUf.setBorder(null);
        textFieldCadUf.setMargin(new java.awt.Insets(2, 20, 2, 6));
        textFieldCadUf.setPreferredSize(new java.awt.Dimension(50, 22));

        labelCadComplemento.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadComplemento.setForeground(new java.awt.Color(255, 255, 255));
        labelCadComplemento.setText("Complemento:");

        textFieldCadComplemento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCadComplemento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldCadComplemento.setBorder(null);
        textFieldCadComplemento.setMargin(new java.awt.Insets(2, 20, 2, 6));
        textFieldCadComplemento.setPreferredSize(new java.awt.Dimension(50, 22));

        labelCadTipo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadTipo.setForeground(new java.awt.Color(255, 255, 255));
        labelCadTipo.setText("Tipo:");

        comboCadTipo.setMaximumRowCount(2);
        comboCadTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urbano", "Rural" }));
        comboCadTipo.setPreferredSize(new java.awt.Dimension(50, 22));
        comboCadTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCadTipoActionPerformed(evt);
            }
        });

        labelCadObservacaoEndereco.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadObservacaoEndereco.setForeground(new java.awt.Color(255, 255, 255));
        labelCadObservacaoEndereco.setText("Observação Endereço:");

        textFieldCadObservacaoEndereco.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCadObservacaoEndereco.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldCadObservacaoEndereco.setBorder(null);
        textFieldCadObservacaoEndereco.setMargin(new java.awt.Insets(2, 20, 2, 6));
        textFieldCadObservacaoEndereco.setPreferredSize(new java.awt.Dimension(50, 22));

        comboCadPessoa.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comboCadPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Física", "Jurídica" }));
        comboCadPessoa.setBorder(null);
        comboCadPessoa.setPreferredSize(new java.awt.Dimension(50, 22));

        labelCadPessoa.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadPessoa.setForeground(new java.awt.Color(255, 255, 255));
        labelCadPessoa.setText("Pessoa:");

        labelCadTelefone.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadTelefone.setForeground(new java.awt.Color(255, 255, 255));
        labelCadTelefone.setText("Telefone:");

        textFieldCadTelefone.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCadTelefone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldCadTelefone.setBorder(null);
        textFieldCadTelefone.setMargin(new java.awt.Insets(2, 20, 2, 6));
        textFieldCadTelefone.setPreferredSize(new java.awt.Dimension(50, 22));

        labelCadContato.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadContato.setForeground(new java.awt.Color(255, 255, 255));
        labelCadContato.setText("Contato:");

        textFieldCadContato.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCadContato.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldCadContato.setBorder(null);
        textFieldCadContato.setMargin(new java.awt.Insets(2, 20, 2, 6));
        textFieldCadContato.setPreferredSize(new java.awt.Dimension(50, 22));

        labelCadObservacaoCliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCadObservacaoCliente.setForeground(new java.awt.Color(255, 255, 255));
        labelCadObservacaoCliente.setText("Observação Cliente:");

        textFieldCadObservacaoCliente.setColumns(100);
        textFieldCadObservacaoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textFieldCadObservacaoCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textFieldCadObservacaoCliente.setBorder(null);
        textFieldCadObservacaoCliente.setMargin(new java.awt.Insets(2, 20, 2, 6));
        textFieldCadObservacaoCliente.setPreferredSize(new java.awt.Dimension(50, 22));

        botaoCadLimpar.setBackground(new java.awt.Color(250, 250, 250));
        botaoCadLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/eraser.png"))); // NOI18N
        botaoCadLimpar.setToolTipText("Apagar Campos");
        botaoCadLimpar.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        botaoCadLimpar.setBorderPainted(false);
        botaoCadLimpar.setMaximumSize(new java.awt.Dimension(38, 38));
        botaoCadLimpar.setPreferredSize(new java.awt.Dimension(36, 36));
        botaoCadLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCenterLayout = new javax.swing.GroupLayout(painelCenter);
        painelCenter.setLayout(painelCenterLayout);
        painelCenterLayout.setHorizontalGroup(
                painelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelCenterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(painelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(painelCenterLayout.createSequentialGroup()
                                                .addComponent(labelCadObservacaoEndereco)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldCadObservacaoEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(painelCenterLayout.createSequentialGroup()
                                                .addGroup(painelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(painelCenterLayout.createSequentialGroup()
                                                                .addComponent(labelCadId)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textFieldCadId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(painelCenterLayout.createSequentialGroup()
                                                                .addComponent(labelCadPessoa)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(comboCadPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(labelCadNome)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textFieldCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(labelCadCpf)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldCadCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addGroup(painelCenterLayout.createSequentialGroup()
                                                .addComponent(labelCadUf)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldCadUf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelCadCep)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldCadCep, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelCadComplemento)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldCadComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelCadTipo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboCadTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(painelCenterLayout.createSequentialGroup()
                                                .addComponent(labelCadTelefone)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldCadTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelCadContato)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldCadContato, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoCadLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(painelCenterLayout.createSequentialGroup()
                                                .addComponent(labelCadLogradouro)
                                                .addGap(9, 9, 9)
                                                .addComponent(textFieldCadLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelCadNumero)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldCadNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelCadBairro)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldCadBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelCadCidade))
                                        .addGroup(painelCenterLayout.createSequentialGroup()
                                                .addComponent(labelCadObservacaoCliente)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldCadObservacaoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(textFieldCadCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCenterLayout.setVerticalGroup(
                painelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelCenterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(painelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelCadId)
                                        .addComponent(textFieldCadId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelCadNome)
                                        .addComponent(textFieldCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelCadCpf)
                                        .addComponent(textFieldCadCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboCadPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelCadPessoa))
                                .addGap(18, 18, 18)
                                .addGroup(painelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelCadObservacaoCliente)
                                        .addComponent(textFieldCadObservacaoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(painelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelCadLogradouro)
                                        .addComponent(textFieldCadLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelCadNumero)
                                        .addComponent(textFieldCadNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelCadBairro)
                                        .addComponent(textFieldCadBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelCadCidade)
                                        .addComponent(textFieldCadCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(painelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelCadUf)
                                        .addComponent(labelCadCep)
                                        .addComponent(textFieldCadCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldCadUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelCadComplemento)
                                        .addComponent(textFieldCadComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelCadTipo)
                                        .addComponent(comboCadTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(painelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelCadObservacaoEndereco)
                                        .addComponent(textFieldCadObservacaoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(painelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelCadTelefone)
                                        .addComponent(textFieldCadTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelCadContato)
                                        .addComponent(textFieldCadContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(12, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCenterLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoCadLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        painelBottom.setBackground(new java.awt.Color(0, 77, 64));

        tabbedPaneCad.setBackground(new java.awt.Color(0, 77, 64));
        tabbedPaneCad.setForeground(new java.awt.Color(255, 255, 255));
        tabbedPaneCad.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N

        painelCadClientes.setBackground(new java.awt.Color(0, 77, 64));

        scrollPaneCadClientes.setBackground(new java.awt.Color(0, 77, 64));

        tableCadClientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tableCadClientes.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Id", "Nome", "CPF/CNPJ", "Observação"
                }
        ));
        scrollPaneCadClientes.setViewportView(tableCadClientes);

        botaoCadClienteProcurar.setBackground(new java.awt.Color(250, 250, 250));
        botaoCadClienteProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/lupa.png"))); // NOI18N
        botaoCadClienteProcurar.setToolTipText("Procurar Cliente");
        botaoCadClienteProcurar.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        botaoCadClienteProcurar.setBorderPainted(false);
        botaoCadClienteProcurar.setPreferredSize(new java.awt.Dimension(38, 38));

        botaoCadClienteDelete.setBackground(new java.awt.Color(250, 250, 250));
        botaoCadClienteDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/delete.png"))); // NOI18N
        botaoCadClienteDelete.setToolTipText("Excluir Cliente");
        botaoCadClienteDelete.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        botaoCadClienteDelete.setBorderPainted(false);
        botaoCadClienteDelete.setPreferredSize(new java.awt.Dimension(38, 38));

        botaoCadClienteAdicionar.setBackground(new java.awt.Color(250, 250, 250));
        botaoCadClienteAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/plus.png"))); // NOI18N
        botaoCadClienteAdicionar.setToolTipText("Adicionar Novo Cliente");
        botaoCadClienteAdicionar.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        botaoCadClienteAdicionar.setBorderPainted(false);
        botaoCadClienteAdicionar.setPreferredSize(new java.awt.Dimension(38, 38));

        botaoCadClienteSalvar.setBackground(new java.awt.Color(250, 250, 250));
        botaoCadClienteSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/pencil.png"))); // NOI18N
        botaoCadClienteSalvar.setToolTipText("Editar Cliente");
        botaoCadClienteSalvar.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        botaoCadClienteSalvar.setBorderPainted(false);
        botaoCadClienteSalvar.setPreferredSize(new java.awt.Dimension(38, 38));

        javax.swing.GroupLayout painelCadClientesLayout = new javax.swing.GroupLayout(painelCadClientes);
        painelCadClientes.setLayout(painelCadClientesLayout);
        painelCadClientesLayout.setHorizontalGroup(
                painelCadClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadClientesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scrollPaneCadClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(painelCadClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botaoCadClienteAdicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botaoCadClienteProcurar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botaoCadClienteSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botaoCadClienteDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );
        painelCadClientesLayout.setVerticalGroup(
                painelCadClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelCadClientesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(painelCadClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scrollPaneCadClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGroup(painelCadClientesLayout.createSequentialGroup()
                                                .addComponent(botaoCadClienteAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoCadClienteProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoCadClienteSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoCadClienteDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 184, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        tabbedPaneCad.addTab("Clientes", painelCadClientes);

        painelCadEnderecos.setBackground(new java.awt.Color(0, 77, 64));

        tableCadEnderecos.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "Nome", "Logradouro", "Numero", "Bairro", "Cidade", "UF", "CEP", "Complemento", "Tipo", "Observação"
                }
        ));
        scrollPaneCadEnderecos.setViewportView(tableCadEnderecos);

        botaoCadEnderecoAdicionar.setBackground(new java.awt.Color(250, 250, 250));
        botaoCadEnderecoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/plus.png"))); // NOI18N
        botaoCadEnderecoAdicionar.setToolTipText("Adicionar Novo Endereço");
        botaoCadEnderecoAdicionar.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        botaoCadEnderecoAdicionar.setBorderPainted(false);
        botaoCadEnderecoAdicionar.setPreferredSize(new java.awt.Dimension(38, 38));
        botaoCadEnderecoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadEnderecoAdicionarActionPerformed(evt);
            }
        });

        botaoCadEnderecoDelete.setBackground(new java.awt.Color(250, 250, 250));
        botaoCadEnderecoDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/delete.png"))); // NOI18N
        botaoCadEnderecoDelete.setToolTipText("Excluir Endereço");
        botaoCadEnderecoDelete.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        botaoCadEnderecoDelete.setBorderPainted(false);
        botaoCadEnderecoDelete.setPreferredSize(new java.awt.Dimension(38, 38));

        botaoCadEnderecoProcurar.setBackground(new java.awt.Color(250, 250, 250));
        botaoCadEnderecoProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/lupa.png"))); // NOI18N
        botaoCadEnderecoProcurar.setToolTipText("Procurar Endereço");
        botaoCadEnderecoProcurar.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        botaoCadEnderecoProcurar.setBorderPainted(false);
        botaoCadEnderecoProcurar.setPreferredSize(new java.awt.Dimension(38, 38));

        botaoCadEnderecoEditar.setBackground(new java.awt.Color(250, 250, 250));
        botaoCadEnderecoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/pencil.png"))); // NOI18N
        botaoCadEnderecoEditar.setToolTipText("Editar Endereço");
        botaoCadEnderecoEditar.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        botaoCadEnderecoEditar.setBorderPainted(false);
        botaoCadEnderecoEditar.setPreferredSize(new java.awt.Dimension(38, 38));

        javax.swing.GroupLayout painelCadEnderecosLayout = new javax.swing.GroupLayout(painelCadEnderecos);
        painelCadEnderecos.setLayout(painelCadEnderecosLayout);
        painelCadEnderecosLayout.setHorizontalGroup(
                painelCadEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadEnderecosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scrollPaneCadEnderecos, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(painelCadEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(botaoCadEnderecoDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoCadEnderecoProcurar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoCadEnderecoAdicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoCadEnderecoEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        painelCadEnderecosLayout.setVerticalGroup(
                painelCadEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelCadEnderecosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(painelCadEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scrollPaneCadEnderecos, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                                        .addGroup(painelCadEnderecosLayout.createSequentialGroup()
                                                .addComponent(botaoCadEnderecoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoCadEnderecoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoCadEnderecoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoCadEnderecoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        tabbedPaneCad.addTab("Endereços", painelCadEnderecos);

        painelCadTelefones.setBackground(new java.awt.Color(0, 77, 64));

        tableCadTelefones.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String [] {
                        "Nome", "Telefone", "Contato"
                }
        ));
        scrollPaneCadTelefones.setViewportView(tableCadTelefones);

        botaoCadTelefoneAdicionar.setBackground(new java.awt.Color(250, 250, 250));
        botaoCadTelefoneAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/plus.png"))); // NOI18N
        botaoCadTelefoneAdicionar.setToolTipText("Adicionar Novo Telefone");
        botaoCadTelefoneAdicionar.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        botaoCadTelefoneAdicionar.setBorderPainted(false);
        botaoCadTelefoneAdicionar.setPreferredSize(new java.awt.Dimension(38, 38));

        botaoCadTelefoneDelete.setBackground(new java.awt.Color(250, 250, 250));
        botaoCadTelefoneDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/delete.png"))); // NOI18N
        botaoCadTelefoneDelete.setToolTipText("Excluir Telefone");
        botaoCadTelefoneDelete.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        botaoCadTelefoneDelete.setBorderPainted(false);
        botaoCadTelefoneDelete.setPreferredSize(new java.awt.Dimension(38, 38));

        botaoCadTelefoneProcurar.setBackground(new java.awt.Color(250, 250, 250));
        botaoCadTelefoneProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/lupa.png"))); // NOI18N
        botaoCadTelefoneProcurar.setToolTipText("Procurar Telefone");
        botaoCadTelefoneProcurar.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        botaoCadTelefoneProcurar.setBorderPainted(false);
        botaoCadTelefoneProcurar.setPreferredSize(new java.awt.Dimension(38, 38));

        botaoCadTelefoneEditar.setBackground(new java.awt.Color(250, 250, 250));
        botaoCadTelefoneEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/pencil.png"))); // NOI18N
        botaoCadTelefoneEditar.setToolTipText("Editar Telefone");
        botaoCadTelefoneEditar.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2, true));
        botaoCadTelefoneEditar.setBorderPainted(false);
        botaoCadTelefoneEditar.setPreferredSize(new java.awt.Dimension(38, 38));

        javax.swing.GroupLayout painelCadTelefonesLayout = new javax.swing.GroupLayout(painelCadTelefones);
        painelCadTelefones.setLayout(painelCadTelefonesLayout);
        painelCadTelefonesLayout.setHorizontalGroup(
                painelCadTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelCadTelefonesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scrollPaneCadTelefones, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(painelCadTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(botaoCadTelefoneDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoCadTelefoneEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoCadTelefoneProcurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoCadTelefoneAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        painelCadTelefonesLayout.setVerticalGroup(
                painelCadTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelCadTelefonesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(painelCadTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scrollPaneCadTelefones, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                                        .addGroup(painelCadTelefonesLayout.createSequentialGroup()
                                                .addComponent(botaoCadTelefoneAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoCadTelefoneProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoCadTelefoneEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoCadTelefoneDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        tabbedPaneCad.addTab("Telefones", painelCadTelefones);

        javax.swing.GroupLayout painelBottomLayout = new javax.swing.GroupLayout(painelBottom);
        painelBottom.setLayout(painelBottomLayout);
        painelBottomLayout.setHorizontalGroup(
                painelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBottomLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tabbedPaneCad))
        );
        painelBottomLayout.setVerticalGroup(
                painelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tabbedPaneCad)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(painelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(painelCenter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(painelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(painelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(painelCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(painelBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void textFieldCadNomeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textFieldCadNumeroActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textFieldCadCidadeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textFieldCadBairroActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void comboCadTipoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void botaoCadEnderecoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textFieldCadIdActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void botaoCadLimparActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void botaoCadVoltarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroClientes dialog = new CadastroClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton botaoCadClienteAdicionar;
    private javax.swing.JButton botaoCadClienteDelete;
    private javax.swing.JToggleButton botaoCadClienteProcurar;
    private javax.swing.JButton botaoCadClienteSalvar;
    private javax.swing.JToggleButton botaoCadEnderecoAdicionar;
    private javax.swing.JToggleButton botaoCadEnderecoDelete;
    private javax.swing.JButton botaoCadEnderecoEditar;
    private javax.swing.JButton botaoCadEnderecoProcurar;
    private javax.swing.JButton botaoCadLimpar;
    private javax.swing.JButton botaoCadTelefoneAdicionar;
    private javax.swing.JButton botaoCadTelefoneDelete;
    private javax.swing.JButton botaoCadTelefoneEditar;
    private javax.swing.JButton botaoCadTelefoneProcurar;
    private javax.swing.JButton botaoCadVoltar;
    private javax.swing.JComboBox<String> comboCadPessoa;
    private javax.swing.JComboBox<String> comboCadTipo;
    private javax.swing.JLabel labelCadBairro;
    private javax.swing.JLabel labelCadCep;
    private javax.swing.JLabel labelCadCidade;
    private javax.swing.JLabel labelCadComplemento;
    private javax.swing.JLabel labelCadContato;
    private javax.swing.JLabel labelCadCpf;
    private javax.swing.JLabel labelCadId;
    private javax.swing.JLabel labelCadLogradouro;
    private javax.swing.JLabel labelCadNome;
    private javax.swing.JLabel labelCadNumero;
    private javax.swing.JLabel labelCadObservacaoCliente;
    private javax.swing.JLabel labelCadObservacaoEndereco;
    private javax.swing.JLabel labelCadPessoa;
    private javax.swing.JLabel labelCadTelefone;
    private javax.swing.JLabel labelCadTipo;
    private javax.swing.JLabel labelCadTitulo;
    private javax.swing.JLabel labelCadUf;
    private javax.swing.JPanel painelBottom;
    private javax.swing.JPanel painelCadClientes;
    private javax.swing.JPanel painelCadEnderecos;
    private javax.swing.JPanel painelCadTelefones;
    private javax.swing.JPanel painelCenter;
    private javax.swing.JPanel painelTop;
    private javax.swing.JScrollPane scrollPaneCadClientes;
    private javax.swing.JScrollPane scrollPaneCadEnderecos;
    private javax.swing.JScrollPane scrollPaneCadTelefones;
    private javax.swing.JTabbedPane tabbedPaneCad;
    private javax.swing.JTable tableCadClientes;
    private javax.swing.JTable tableCadEnderecos;
    private javax.swing.JTable tableCadTelefones;
    private javax.swing.JTextField textFieldCadBairro;
    private javax.swing.JTextField textFieldCadCep;
    private javax.swing.JTextField textFieldCadCidade;
    private javax.swing.JTextField textFieldCadComplemento;
    private javax.swing.JTextField textFieldCadContato;
    private javax.swing.JTextField textFieldCadCpf;
    private javax.swing.JTextField textFieldCadId;
    private javax.swing.JTextField textFieldCadLogradouro;
    private javax.swing.JTextField textFieldCadNome;
    private javax.swing.JTextField textFieldCadNumero;
    private javax.swing.JTextField textFieldCadObservacaoCliente;
    private javax.swing.JTextField textFieldCadObservacaoEndereco;
    private javax.swing.JTextField textFieldCadTelefone;
    private javax.swing.JTextField textFieldCadUf;
    // End of variables declaration


    public JScrollPane getScrollPaneCadClientes() {
        return scrollPaneCadClientes;
    }

    public JScrollPane getScrollPaneCadEnderecos() {
        return scrollPaneCadEnderecos;
    }

    public JScrollPane getScrollPaneCadTelefones() {
        return scrollPaneCadTelefones;
    }

    public JTabbedPane getTabbedPaneCad() {
        return tabbedPaneCad;
    }

    public JTable getTableCadEnderecos() {
        return tableCadEnderecos;
    }

    public JPanel getPainelCenter() {
        return painelCenter;
    }

    public JPanel getPainelTop() {
        return painelTop;
    }

    public JPanel getPainelBottom() {
        return painelBottom;
    }

    public JLabel getLabelCadBairro() {
        return labelCadBairro;
    }

    public JPanel getPainelCadClientes() {
        return painelCadClientes;
    }

    public JPanel getPainelCadEnderecos() {
        return painelCadEnderecos;
    }

    public JPanel getPainelCadTelefones() {
        return painelCadTelefones;
    }

    public JLabel getLabelCadTitulo() {
        return labelCadTitulo;
    }

    public JComboBox[] getTodosComboBox(){
        return new JComboBox[]{
                comboCadPessoa,
                comboCadTipo
        };
    }

    public JTextField[] getTodosJTextFields(){
        return new JTextField[]{
                textFieldCadBairro,
                textFieldCadCep,
                textFieldCadCidade,
                textFieldCadComplemento,
                textFieldCadContato,
                textFieldCadCpf,
                textFieldCadId,
                textFieldCadLogradouro,
                textFieldCadNome,
                textFieldCadNumero,
                textFieldCadObservacaoCliente,
                textFieldCadObservacaoEndereco,
                textFieldCadTelefone,
                textFieldCadUf
        };
    }

    public JTextField[] getClienteJTextFields(){
        return new JTextField[]{
                textFieldCadId,
                textFieldCadNome,
                textFieldCadCpf,
                textFieldCadObservacaoCliente,
        };
    }

    public JTextField[] getEnderecoJTextFields(){
        return new JTextField[]{
                textFieldCadLogradouro,
                textFieldCadNumero,
                textFieldCadBairro,
                textFieldCadObservacaoEndereco,
                textFieldCadUf,
                textFieldCadCep,
                textFieldCadCidade,
                textFieldCadComplemento
        };
    }



    public JTable getTableCadTelefones() {
        return tableCadTelefones;
    }

    public JTable getTableCadClientes() {
        return tableCadClientes;
    }

    public JButton getBotaoCadClienteAdicionar() {
        return botaoCadClienteAdicionar;
    }

    public JButton getBotaoCadClienteDelete() {
        return botaoCadClienteDelete;
    }

    public JToggleButton getBotaoCadClienteProcurar() {
        return botaoCadClienteProcurar;
    }

    public JButton getBotaoCadClienteSalvar() {
        return botaoCadClienteSalvar;
    }

    public JToggleButton getBotaoCadEnderecoAdicionar() {
        return botaoCadEnderecoAdicionar;
    }

    public JToggleButton getBotaoCadEnderecoDelete() {
        return botaoCadEnderecoDelete;
    }

    public JButton getBotaoCadEnderecoEditar() {
        return botaoCadEnderecoEditar;
    }

    public JButton getBotaoCadEnderecoProcurar() {
        return botaoCadEnderecoProcurar;
    }

    public JButton getBotaoCadLimpar() {
        return botaoCadLimpar;
    }

    public JButton getBotaoCadTelefoneAdicionar() {
        return botaoCadTelefoneAdicionar;
    }

    public JButton getBotaoCadTelefoneDelete() {
        return botaoCadTelefoneDelete;
    }

    public JButton getBotaoCadTelefoneEditar() {
        return botaoCadTelefoneEditar;
    }

    public JButton getBotaoCadTelefoneProcurar() {
        return botaoCadTelefoneProcurar;
    }

    public JButton getBotaoCadVoltar() {
        return botaoCadVoltar;
    }

    public Regime getComboCadPessoa() {
        String selecionado = (String) comboCadPessoa.getSelectedItem();
        if ("Física".equals(selecionado)) {
            return Regime.PESSOA_FISICA;
        } else if ("Jurídica".equals(selecionado)) {
            return Regime.PESSOA_JURIDICA;
        }
        return null;
    }



    public Tipo getComboCadTipo() {
        String selecionado = (String) comboCadTipo.getSelectedItem();

        if (selecionado == null || selecionado.isEmpty()) {
            return null;  // Ou um valor default como Tipo.UNKNOWN, se houver
        }

        switch (selecionado) {
            case "Urbano":
                return Tipo.URBANO;
            case "Rural":
                return Tipo.RURAL;
            default:
                // Retorne um valor default ou lance uma exceção, dependendo do seu caso
                return null; // ou Tipo.UNKNOWN
        }
    }

    public String getTextFieldCadBairroString() {
        return textFieldCadBairro.getText();
    }

    public String getTextFieldCadCepString() {
        return textFieldCadCep.getText();
    }

    public String getTextFieldCadCidadeString() {
        return textFieldCadCidade.getText();
    }

    public String getTextFieldCadComplementoString() {
        return textFieldCadComplemento.getText();
    }

    public JTextField getTextFieldCadContato() {
        return textFieldCadContato;
    }

    public String getTextFieldCadCpfString() {
        return textFieldCadCpf.getText();
    }

    public JTextField getTextFieldCadId() {
        return textFieldCadId;
    }
    public Long getTextFieldCadIdLong() {
        return Long.valueOf(textFieldCadId.getText());
    }

    public String getTextFieldCadLogradouroString() {
        return textFieldCadLogradouro.getText();
    }

    public String getTextFieldCadNomeString() {
        return textFieldCadNome.getText();
    }

    public String getTextFieldCadNumeroString() {
        return textFieldCadNumero.getText();
    }

    public String getTextFieldCadObservacaoClienteString() {
        return textFieldCadObservacaoCliente.getText();
    }

    public String getTextFieldCadObservacaoEnderecoString() {
        return textFieldCadObservacaoEndereco.getText();
    }

    public JTextField getTextFieldCadTelefone() {
        return textFieldCadTelefone;
    }

    public String getTextFieldCadUfString() {
        return textFieldCadUf.getText();
    }

    public JTextField getTextFieldCadBairro() {
        return textFieldCadBairro;
    }

    public JTextField getTextFieldCadCep() {
        return textFieldCadCep;
    }

    public JTextField getTextFieldCadCidade() {
        return textFieldCadCidade;
    }

    public JTextField getTextFieldCadComplemento() {
        return textFieldCadComplemento;
    }

    public JTextField getTextFieldCadCpf() {
        return textFieldCadCpf;
    }

    public JTextField getTextFieldCadLogradouro() {
        return textFieldCadLogradouro;
    }

    public JTextField getTextFieldCadNome() {
        return textFieldCadNome;
    }

    public JTextField getTextFieldCadNumero() {
        return textFieldCadNumero;
    }

    public JTextField getTextFieldCadObservacaoCliente() {
        return textFieldCadObservacaoCliente;
    }

    public JTextField getTextFieldCadObservacaoEndereco() {
        return textFieldCadObservacaoEndereco;
    }

    public JTextField getTextFieldCadUf() {
        return textFieldCadUf;
    }
}
