package com.diskchop.view;

import com.diskchop.model.entity.Regime;
import com.diskchop.model.entity.StatusCliente;
import com.diskchop.model.entity.Tipo;
import com.formdev.flatlaf.FlatDarkLaf;

import javax.swing.*;
/**
 *
 * @author Yuri
 */
public class Cadastro extends javax.swing.JDialog {

    /**
     * Creates new form Cadastro
     */
    public Cadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        paneltop = new javax.swing.JPanel();
        labelTituloClientes = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        panelClientes = new javax.swing.JPanel();
        scrollPaneClientes = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        textFieldNome = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        labelPanelClientes = new javax.swing.JLabel();
        botaoSalvarCliente = new javax.swing.JButton();
        botaoLimparCampos = new javax.swing.JButton();
        botaoNovoCliente = new javax.swing.JButton();
        botaoBuscarCliente = new javax.swing.JButton();
        labelCpf = new javax.swing.JLabel();
        textFieldCpf = new javax.swing.JTextField();
        labelObsClientes = new javax.swing.JLabel();
        textFieldObsCLiente = new javax.swing.JTextField();
        labelId = new javax.swing.JLabel();
        textFieldId = new javax.swing.JTextField();
        comboRegime = new javax.swing.JComboBox<>();
        labelListaClientes = new javax.swing.JLabel();
        labelRegime = new javax.swing.JLabel();
        labelStatusCliente = new javax.swing.JLabel();
        comboStatusCliente = new javax.swing.JComboBox<>();
        botaoExcluirCliente = new javax.swing.JButton();
        panelEnderecos = new javax.swing.JPanel();
        scrollPaneEnderecos = new javax.swing.JScrollPane();
        tableEnderecos = new javax.swing.JTable();
        labelPanelEnderecos = new javax.swing.JLabel();
        comboArea = new javax.swing.JComboBox<>();
        labelBairro = new javax.swing.JLabel();
        textFieldBairro = new javax.swing.JTextField();
        labelCidade = new javax.swing.JLabel();
        textFieldCidade = new javax.swing.JTextField();
        labelArea = new javax.swing.JLabel();
        textFieldComplemento = new javax.swing.JTextField();
        labelComplemento = new javax.swing.JLabel();
        textFieldObsEnderecos = new javax.swing.JTextField();
        labelObsEndereco = new javax.swing.JLabel();
        textFieldCep = new javax.swing.JTextField();
        labelCep = new javax.swing.JLabel();
        botaoAdicionarEndereco = new javax.swing.JButton();
        botaoExcluirEndereco = new javax.swing.JButton();
        botaoBuscarEndereco = new javax.swing.JButton();
        labelListaEnderecos = new javax.swing.JLabel();
        labelNumeroEnderco = new javax.swing.JLabel();
        labelLogradouro = new javax.swing.JLabel();
        textFieldLogradouro = new javax.swing.JTextField();
        textFieldNumeroEndereco = new javax.swing.JTextField();
        botaoSalvarEndereco = new javax.swing.JButton();
        labelIdEndereco = new javax.swing.JLabel();
        textFieldIdEndereco = new javax.swing.JTextField();
        panelTelefones = new javax.swing.JPanel();
        scrollPaneTelefones = new javax.swing.JScrollPane();
        tableTelefones = new javax.swing.JTable();
        labelPanelTelefones = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        textFieldTelefone = new javax.swing.JTextField();
        labelContato = new javax.swing.JLabel();
        textFieldContato = new javax.swing.JTextField();
        botaoBuscarTelefone = new javax.swing.JButton();
        botaoSalvarTelefone = new javax.swing.JButton();
        botaoAdicionarTelefone = new javax.swing.JButton();
        botaoExcluirTelefone = new javax.swing.JButton();
        labelListaTelefones = new javax.swing.JLabel();
        textFieldIdTelefone = new javax.swing.JTextField();
        labelIdTelefone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(20, 20, 25));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);
        setSize(new java.awt.Dimension(954, 851));

        panelBackground.setBackground(new java.awt.Color(20, 20, 25));

        paneltop.setBackground(new java.awt.Color(30, 30, 35));

        labelTituloClientes.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelTituloClientes.setForeground(new java.awt.Color(235, 235, 235));
        labelTituloClientes.setText("CADASTRO DE CLIENTES");

        botaoVoltar.setBackground(new java.awt.Color(30, 30, 35));
        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/voltar.png"))); // NOI18N
        botaoVoltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60), 2));
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneltopLayout = new javax.swing.GroupLayout(paneltop);
        paneltop.setLayout(paneltopLayout);
        paneltopLayout.setHorizontalGroup(
                paneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneltopLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(botaoVoltar)
                                .addGap(18, 18, 18)
                                .addComponent(labelTituloClientes)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneltopLayout.setVerticalGroup(
                paneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneltopLayout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addGroup(paneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botaoVoltar)
                                        .addComponent(labelTituloClientes)))
        );

        panelClientes.setBackground(new java.awt.Color(20, 20, 25));

        scrollPaneClientes.setBackground(new java.awt.Color(60, 60, 60));
        scrollPaneClientes.setBorder(null);

        tableClientes.setBackground(new java.awt.Color(20, 20, 25));
        tableClientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tableClientes.setForeground(new java.awt.Color(250, 250, 250));
        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        tableClientes.setGridColor(new java.awt.Color(60, 60, 65));
        scrollPaneClientes.setViewportView(tableClientes);

        textFieldNome.setBackground(new java.awt.Color(30, 30, 35));
        textFieldNome.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldNome.setForeground(new java.awt.Color(235, 235, 235));
        textFieldNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldNome.setCaretColor(new java.awt.Color(235, 235, 235));
        textFieldNome.setPreferredSize(new java.awt.Dimension(0, 25));

        labelNome.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(255, 200, 87));
        labelNome.setText("NOME:");

        labelPanelClientes.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        labelPanelClientes.setForeground(new java.awt.Color(235, 235, 235));
        labelPanelClientes.setText("CLIENTES");

        botaoSalvarCliente.setBackground(new java.awt.Color(40, 40, 45));
        botaoSalvarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/diskette.png"))); // NOI18N
        botaoSalvarCliente.setToolTipText("Salvar Cliente");
        botaoSalvarCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 2, true));

        botaoLimparCampos.setBackground(new java.awt.Color(40, 40, 45));
        botaoLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/eraser.png"))); // NOI18N
        botaoLimparCampos.setToolTipText("Limpar Campos de Preenchimento");
        botaoLimparCampos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 2, true));

        botaoNovoCliente.setBackground(new java.awt.Color(40, 40, 45));
        botaoNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/adicionar.png"))); // NOI18N
        botaoNovoCliente.setToolTipText("Adicionar Novo Cliente");
        botaoNovoCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 2, true));

        botaoBuscarCliente.setBackground(new java.awt.Color(40, 40, 45));
        botaoBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/lupa.png"))); // NOI18N
        botaoBuscarCliente.setToolTipText("Buscar Cliente Por Id");
        botaoBuscarCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 2, true));

        labelCpf.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCpf.setForeground(new java.awt.Color(255, 200, 87));
        labelCpf.setText("CPF/CNPJ:");

        textFieldCpf.setBackground(new java.awt.Color(30, 30, 35));
        textFieldCpf.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldCpf.setForeground(new java.awt.Color(235, 235, 235));
        textFieldCpf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldCpf.setCaretColor(new java.awt.Color(235, 235, 235));
        textFieldCpf.setPreferredSize(new java.awt.Dimension(0, 25));

        labelObsClientes.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelObsClientes.setForeground(new java.awt.Color(255, 200, 87));
        labelObsClientes.setText("OBS:");

        textFieldObsCLiente.setBackground(new java.awt.Color(30, 30, 35));
        textFieldObsCLiente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldObsCLiente.setForeground(new java.awt.Color(235, 235, 235));
        textFieldObsCLiente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldObsCLiente.setCaretColor(new java.awt.Color(235, 235, 235));
        textFieldObsCLiente.setPreferredSize(new java.awt.Dimension(0, 25));
        textFieldObsCLiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldObsCLienteActionPerformed(evt);
            }
        });

        labelId.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelId.setForeground(new java.awt.Color(255, 200, 87));
        labelId.setText("ID:");

        textFieldId.setBackground(new java.awt.Color(30, 30, 35));
        textFieldId.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldId.setForeground(new java.awt.Color(235, 235, 235));
        textFieldId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldId.setCaretColor(new java.awt.Color(235, 235, 235));
        textFieldId.setPreferredSize(new java.awt.Dimension(0, 25));

        comboRegime.setBackground(new java.awt.Color(30, 30, 35));
        comboRegime.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        comboRegime.setForeground(new java.awt.Color(235, 235, 235));
        comboRegime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Física", "Jurídica" }));
        comboRegime.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        comboRegime.setPreferredSize(new java.awt.Dimension(0, 25));

        labelListaClientes.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelListaClientes.setForeground(new java.awt.Color(235, 235, 235));
        labelListaClientes.setText("LISTA DE CLIENTES");

        labelRegime.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelRegime.setForeground(new java.awt.Color(255, 200, 87));
        labelRegime.setText("REGIME:");

        labelStatusCliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelStatusCliente.setForeground(new java.awt.Color(255, 200, 87));
        labelStatusCliente.setText("STATUS:");

        comboStatusCliente.setBackground(new java.awt.Color(30, 30, 35));
        comboStatusCliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        comboStatusCliente.setForeground(new java.awt.Color(235, 235, 235));
        comboStatusCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Suspenso" }));
        comboStatusCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 65)));
        comboStatusCliente.setPreferredSize(new java.awt.Dimension(97, 25));

        botaoExcluirCliente.setBackground(new java.awt.Color(40, 40, 45));
        botaoExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/bin.png"))); // NOI18N
        botaoExcluirCliente.setToolTipText("Excluir Cliente");
        botaoExcluirCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 2, true));

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
                panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelClientesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scrollPaneClientes, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelClientesLayout.createSequentialGroup()
                                                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelListaClientes)
                                                        .addComponent(labelPanelClientes))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                                                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(panelClientesLayout.createSequentialGroup()
                                                                .addComponent(labelCpf)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(textFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(labelObsClientes)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textFieldObsCLiente, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(labelStatusCliente)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(comboStatusCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(panelClientesLayout.createSequentialGroup()
                                                                .addComponent(labelId)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(labelRegime)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(comboRegime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(labelNome)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelClientesLayout.createSequentialGroup()
                                                                .addComponent(botaoBuscarCliente)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(botaoNovoCliente)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(botaoSalvarCliente)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(botaoLimparCampos))
                                                        .addComponent(botaoExcluirCliente))))
                                .addContainerGap())
        );
        panelClientesLayout.setVerticalGroup(
                panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelClientesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelPanelClientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelClientesLayout.createSequentialGroup()
                                                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(botaoBuscarCliente)
                                                        .addComponent(botaoNovoCliente)
                                                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(labelId)
                                                                .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(comboRegime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(labelRegime)
                                                                .addComponent(labelNome)
                                                                .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(17, 17, 17)
                                                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(labelCpf)
                                                        .addComponent(textFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelObsClientes)
                                                        .addComponent(textFieldObsCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelStatusCliente)
                                                        .addComponent(comboStatusCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(botaoExcluirCliente)))
                                        .addComponent(botaoLimparCampos)
                                        .addComponent(botaoSalvarCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelListaClientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPaneClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        panelEnderecos.setBackground(new java.awt.Color(20, 20, 25));

        scrollPaneEnderecos.setBackground(new java.awt.Color(60, 60, 60));
        scrollPaneEnderecos.setBorder(null);

        tableEnderecos.setBackground(new java.awt.Color(20, 20, 25));
        tableEnderecos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tableEnderecos.setForeground(new java.awt.Color(235, 235, 235));
        tableEnderecos.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        tableEnderecos.setGridColor(new java.awt.Color(60, 60, 65));
        scrollPaneEnderecos.setViewportView(tableEnderecos);

        labelPanelEnderecos.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        labelPanelEnderecos.setForeground(new java.awt.Color(235, 235, 235));
        labelPanelEnderecos.setText("ENDEREÇOS");

        comboArea.setBackground(new java.awt.Color(30, 30, 35));
        comboArea.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        comboArea.setForeground(new java.awt.Color(235, 235, 235));
        comboArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urbano", "Rural" }));
        comboArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        comboArea.setPreferredSize(new java.awt.Dimension(0, 25));

        labelBairro.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelBairro.setForeground(new java.awt.Color(255, 200, 87));
        labelBairro.setText("BAIRRO:");

        textFieldBairro.setBackground(new java.awt.Color(30, 30, 35));
        textFieldBairro.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldBairro.setForeground(new java.awt.Color(235, 235, 235));
        textFieldBairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldBairro.setCaretColor(new java.awt.Color(235, 235, 235));
        textFieldBairro.setPreferredSize(new java.awt.Dimension(0, 25));

        labelCidade.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCidade.setForeground(new java.awt.Color(255, 200, 87));
        labelCidade.setText("CIDADE:");

        textFieldCidade.setBackground(new java.awt.Color(30, 30, 35));
        textFieldCidade.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldCidade.setForeground(new java.awt.Color(235, 235, 235));
        textFieldCidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldCidade.setCaretColor(new java.awt.Color(235, 235, 235));
        textFieldCidade.setPreferredSize(new java.awt.Dimension(0, 25));

        labelArea.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelArea.setForeground(new java.awt.Color(255, 200, 87));
        labelArea.setText("ÁREA:");

        textFieldComplemento.setBackground(new java.awt.Color(30, 30, 35));
        textFieldComplemento.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldComplemento.setForeground(new java.awt.Color(235, 235, 235));
        textFieldComplemento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldComplemento.setCaretColor(new java.awt.Color(235, 235, 235));
        textFieldComplemento.setPreferredSize(new java.awt.Dimension(0, 25));
        textFieldComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldComplementoActionPerformed(evt);
            }
        });

        labelComplemento.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelComplemento.setForeground(new java.awt.Color(255, 200, 87));
        labelComplemento.setText("COMPLEMENTO:");

        textFieldObsEnderecos.setBackground(new java.awt.Color(30, 30, 35));
        textFieldObsEnderecos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldObsEnderecos.setForeground(new java.awt.Color(235, 235, 235));
        textFieldObsEnderecos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldObsEnderecos.setCaretColor(new java.awt.Color(235, 235, 235));
        textFieldObsEnderecos.setPreferredSize(new java.awt.Dimension(0, 25));

        labelObsEndereco.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelObsEndereco.setForeground(new java.awt.Color(255, 200, 87));
        labelObsEndereco.setText("OBS:");

        textFieldCep.setBackground(new java.awt.Color(30, 30, 35));
        textFieldCep.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldCep.setForeground(new java.awt.Color(235, 235, 235));
        textFieldCep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldCep.setCaretColor(new java.awt.Color(235, 235, 235));
        textFieldCep.setPreferredSize(new java.awt.Dimension(0, 25));

        labelCep.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCep.setForeground(new java.awt.Color(255, 200, 87));
        labelCep.setText("CEP:");

        botaoAdicionarEndereco.setBackground(new java.awt.Color(40, 40, 45));
        botaoAdicionarEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/adicionar.png"))); // NOI18N
        botaoAdicionarEndereco.setToolTipText("Adicionar Novo Endereço");
        botaoAdicionarEndereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 2, true));

        botaoExcluirEndereco.setBackground(new java.awt.Color(40, 40, 45));
        botaoExcluirEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/bin.png"))); // NOI18N
        botaoExcluirEndereco.setToolTipText("Excluir Endereço");
        botaoExcluirEndereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 2, true));

        botaoBuscarEndereco.setBackground(new java.awt.Color(40, 40, 45));
        botaoBuscarEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/lupa.png"))); // NOI18N
        botaoBuscarEndereco.setToolTipText("Pesquisar Endereços do Cliente");
        botaoBuscarEndereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 2, true));

        labelListaEnderecos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelListaEnderecos.setForeground(new java.awt.Color(235, 235, 235));
        labelListaEnderecos.setText("LISTA ENDEREÇOS");

        labelNumeroEnderco.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelNumeroEnderco.setForeground(new java.awt.Color(255, 200, 87));
        labelNumeroEnderco.setText("Nº:");

        labelLogradouro.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelLogradouro.setForeground(new java.awt.Color(255, 200, 87));
        labelLogradouro.setText("LOGRADOURO:");

        textFieldLogradouro.setBackground(new java.awt.Color(30, 30, 35));
        textFieldLogradouro.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldLogradouro.setForeground(new java.awt.Color(235, 235, 235));
        textFieldLogradouro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldLogradouro.setCaretColor(new java.awt.Color(235, 235, 235));
        textFieldLogradouro.setPreferredSize(new java.awt.Dimension(0, 25));

        textFieldNumeroEndereco.setBackground(new java.awt.Color(30, 30, 35));
        textFieldNumeroEndereco.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldNumeroEndereco.setForeground(new java.awt.Color(235, 235, 235));
        textFieldNumeroEndereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldNumeroEndereco.setCaretColor(new java.awt.Color(235, 235, 235));
        textFieldNumeroEndereco.setPreferredSize(new java.awt.Dimension(0, 25));

        botaoSalvarEndereco.setBackground(new java.awt.Color(40, 40, 45));
        botaoSalvarEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/diskette.png"))); // NOI18N
        botaoSalvarEndereco.setToolTipText("Salvar Endereço");
        botaoSalvarEndereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 2, true));

        labelIdEndereco.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelIdEndereco.setForeground(new java.awt.Color(255, 200, 87));
        labelIdEndereco.setText("ID:");

        textFieldIdEndereco.setEditable(false);
        textFieldIdEndereco.setBackground(new java.awt.Color(30, 30, 35));
        textFieldIdEndereco.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldIdEndereco.setForeground(new java.awt.Color(235, 235, 235));
        textFieldIdEndereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldIdEndereco.setPreferredSize(new java.awt.Dimension(0, 25));
        textFieldIdEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEnderecosLayout = new javax.swing.GroupLayout(panelEnderecos);
        panelEnderecos.setLayout(panelEnderecosLayout);
        panelEnderecosLayout.setHorizontalGroup(
                panelEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelEnderecosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEnderecosLayout.createSequentialGroup()
                                                .addGroup(panelEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelEnderecosLayout.createSequentialGroup()
                                                                .addComponent(labelCep)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(textFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(labelArea)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(comboArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(labelObsEndereco)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(textFieldObsEnderecos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEnderecosLayout.createSequentialGroup()
                                                                .addComponent(labelComplemento)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(labelBairro)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(labelCidade)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textFieldCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                                                        .addGroup(panelEnderecosLayout.createSequentialGroup()
                                                                .addComponent(labelIdEndereco)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textFieldIdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(labelLogradouro)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textFieldLogradouro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(labelNumeroEnderco)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textFieldNumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, Short.MAX_VALUE)
                                                .addComponent(botaoBuscarEndereco)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoAdicionarEndereco)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoSalvarEndereco)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoExcluirEndereco))
                                        .addComponent(scrollPaneEnderecos, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelEnderecosLayout.createSequentialGroup()
                                                .addGroup(panelEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelPanelEnderecos)
                                                        .addComponent(labelListaEnderecos))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        panelEnderecosLayout.setVerticalGroup(
                panelEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelEnderecosLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelPanelEnderecos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelEnderecosLayout.createSequentialGroup()
                                                .addGroup(panelEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(botaoAdicionarEndereco)
                                                        .addGroup(panelEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(labelLogradouro)
                                                                .addComponent(textFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(labelNumeroEnderco)
                                                                .addComponent(textFieldNumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(labelIdEndereco)
                                                                .addComponent(textFieldIdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(botaoBuscarEndereco))
                                                .addGap(18, 18, 18)
                                                .addGroup(panelEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(labelBairro)
                                                        .addComponent(textFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelComplemento)
                                                        .addComponent(textFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelCidade)
                                                        .addComponent(textFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29)
                                                .addGroup(panelEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(labelCep)
                                                        .addComponent(textFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelArea)
                                                        .addComponent(comboArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelObsEndereco)
                                                        .addComponent(textFieldObsEnderecos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(botaoExcluirEndereco)
                                        .addComponent(botaoSalvarEndereco))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelListaEnderecos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPaneEnderecos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTelefones.setBackground(new java.awt.Color(20, 20, 25));

        scrollPaneTelefones.setBorder(null);

        tableTelefones.setBackground(new java.awt.Color(20, 20, 25));
        tableTelefones.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tableTelefones.setForeground(new java.awt.Color(235, 235, 235));
        tableTelefones.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        tableTelefones.setGridColor(new java.awt.Color(60, 60, 65));
        scrollPaneTelefones.setViewportView(tableTelefones);

        labelPanelTelefones.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        labelPanelTelefones.setForeground(new java.awt.Color(235, 235, 235));
        labelPanelTelefones.setText("TELEFONES");

        labelTelefone.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelTelefone.setForeground(new java.awt.Color(255, 200, 87));
        labelTelefone.setText("TELEFONE:");

        textFieldTelefone.setBackground(new java.awt.Color(30, 30, 35));
        textFieldTelefone.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldTelefone.setForeground(new java.awt.Color(235, 235, 235));
        textFieldTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldTelefone.setCaretColor(new java.awt.Color(235, 235, 235));
        textFieldTelefone.setPreferredSize(new java.awt.Dimension(0, 25));

        labelContato.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelContato.setForeground(new java.awt.Color(255, 200, 87));
        labelContato.setText("CONTATO:");

        textFieldContato.setBackground(new java.awt.Color(30, 30, 35));
        textFieldContato.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldContato.setForeground(new java.awt.Color(235, 235, 235));
        textFieldContato.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldContato.setCaretColor(new java.awt.Color(235, 235, 235));
        textFieldContato.setPreferredSize(new java.awt.Dimension(0, 25));
        textFieldContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldContatoActionPerformed(evt);
            }
        });

        botaoBuscarTelefone.setBackground(new java.awt.Color(40, 40, 45));
        botaoBuscarTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/lupa.png"))); // NOI18N
        botaoBuscarTelefone.setToolTipText("Buscar Telefones do Cliente");
        botaoBuscarTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 2, true));

        botaoSalvarTelefone.setBackground(new java.awt.Color(40, 40, 45));
        botaoSalvarTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/diskette.png"))); // NOI18N
        botaoSalvarTelefone.setToolTipText("Salvar Telefone");
        botaoSalvarTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 2, true));

        botaoAdicionarTelefone.setBackground(new java.awt.Color(40, 40, 45));
        botaoAdicionarTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/adicionar.png"))); // NOI18N
        botaoAdicionarTelefone.setToolTipText("Adicionar Telefone");
        botaoAdicionarTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 2, true));

        botaoExcluirTelefone.setBackground(new java.awt.Color(40, 40, 45));
        botaoExcluirTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/bin.png"))); // NOI18N
        botaoExcluirTelefone.setToolTipText("Excluir Telefone");
        botaoExcluirTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 2, true));

        labelListaTelefones.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelListaTelefones.setForeground(new java.awt.Color(235, 235, 235));
        labelListaTelefones.setText("LISTA TELEFONES");

        textFieldIdTelefone.setEditable(false);
        textFieldIdTelefone.setBackground(new java.awt.Color(30, 30, 35));
        textFieldIdTelefone.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldIdTelefone.setForeground(new java.awt.Color(235, 235, 235));
        textFieldIdTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(60, 60, 65), 1, true));
        textFieldIdTelefone.setPreferredSize(new java.awt.Dimension(0, 25));

        labelIdTelefone.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelIdTelefone.setForeground(new java.awt.Color(255, 200, 87));
        labelIdTelefone.setText("ID:");

        javax.swing.GroupLayout panelTelefonesLayout = new javax.swing.GroupLayout(panelTelefones);
        panelTelefones.setLayout(panelTelefonesLayout);
        panelTelefonesLayout.setHorizontalGroup(
                panelTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTelefonesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(scrollPaneTelefones)
                                        .addGroup(panelTelefonesLayout.createSequentialGroup()
                                                .addGroup(panelTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelPanelTelefones)
                                                        .addComponent(labelListaTelefones))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(panelTelefonesLayout.createSequentialGroup()
                                                .addComponent(labelIdTelefone)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldIdTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelTelefone)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelContato)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textFieldContato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoBuscarTelefone)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoAdicionarTelefone)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoSalvarTelefone)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoExcluirTelefone)))
                                .addContainerGap())
        );
        panelTelefonesLayout.setVerticalGroup(
                panelTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTelefonesLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelPanelTelefones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelContato)
                                        .addComponent(textFieldContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botaoAdicionarTelefone)
                                        .addComponent(botaoSalvarTelefone)
                                        .addComponent(botaoExcluirTelefone)
                                        .addComponent(botaoBuscarTelefone)
                                        .addGroup(panelTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(labelIdTelefone)
                                                .addComponent(textFieldIdTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelTelefone)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelListaTelefones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPaneTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(paneltop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelEnderecos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelTelefones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addComponent(paneltop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelEnderecos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>


    private void textFieldContatoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textFieldObsCLienteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textFieldComplementoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textFieldIdEnderecoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                UIManager.setLookAndFeel(new FlatDarkLaf());  // Para um tema escuro

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cadastro dialog = new Cadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton botaoAdicionarEndereco;
    private javax.swing.JButton botaoAdicionarTelefone;
    private javax.swing.JButton botaoBuscarCliente;
    private javax.swing.JButton botaoBuscarEndereco;
    private javax.swing.JButton botaoBuscarTelefone;
    private javax.swing.JButton botaoExcluirCliente;
    private javax.swing.JButton botaoExcluirEndereco;
    private javax.swing.JButton botaoExcluirTelefone;
    private javax.swing.JButton botaoLimparCampos;
    private javax.swing.JButton botaoNovoCliente;
    private javax.swing.JButton botaoSalvarCliente;
    private javax.swing.JButton botaoSalvarEndereco;
    private javax.swing.JButton botaoSalvarTelefone;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox<String> comboArea;
    private javax.swing.JComboBox<String> comboRegime;
    private javax.swing.JComboBox<String> comboStatusCliente;
    private javax.swing.JLabel labelArea;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCep;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelComplemento;
    private javax.swing.JLabel labelContato;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelIdEndereco;
    private javax.swing.JLabel labelIdTelefone;
    private javax.swing.JLabel labelListaClientes;
    private javax.swing.JLabel labelListaEnderecos;
    private javax.swing.JLabel labelListaTelefones;
    private javax.swing.JLabel labelLogradouro;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumeroEnderco;
    private javax.swing.JLabel labelObsClientes;
    private javax.swing.JLabel labelObsEndereco;
    private javax.swing.JLabel labelPanelClientes;
    private javax.swing.JLabel labelPanelEnderecos;
    private javax.swing.JLabel labelPanelTelefones;
    private javax.swing.JLabel labelRegime;
    private javax.swing.JLabel labelStatusCliente;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTituloClientes;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelEnderecos;
    private javax.swing.JPanel panelTelefones;
    private javax.swing.JPanel paneltop;
    private javax.swing.JScrollPane scrollPaneClientes;
    private javax.swing.JScrollPane scrollPaneEnderecos;
    private javax.swing.JScrollPane scrollPaneTelefones;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTable tableEnderecos;
    private javax.swing.JTable tableTelefones;
    private javax.swing.JTextField textFieldBairro;
    private javax.swing.JTextField textFieldCep;
    private javax.swing.JTextField textFieldCidade;
    private javax.swing.JTextField textFieldComplemento;
    private javax.swing.JTextField textFieldContato;
    private javax.swing.JTextField textFieldCpf;
    private javax.swing.JTextField textFieldId;
    private javax.swing.JTextField textFieldIdEndereco;
    private javax.swing.JTextField textFieldIdTelefone;
    private javax.swing.JTextField textFieldLogradouro;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldNumeroEndereco;
    private javax.swing.JTextField textFieldObsCLiente;
    private javax.swing.JTextField textFieldObsEnderecos;
    private javax.swing.JTextField textFieldTelefone;
    // End of variables declaration

    public Tipo getComboTipo(){
        String selecionado = (String) comboArea.getSelectedItem();
        if ("Urbano".equals(selecionado)) {
            return Tipo.URBANO;
        } else if ("Rural".equals(selecionado)) {
            return Tipo.RURAL;
        }
        return null;
    }

    public StatusCliente getComboStatusCliente(){
        String selecionado = (String) comboStatusCliente.getSelectedItem();
        if ("Ativo".equals(selecionado)) {
            return StatusCliente.ATIVO;
        } else if ("Suspenso".equals(selecionado)) {
            return StatusCliente.SUSPENSO;
        }
        return null;
    }

    public Regime getComboCadPessoa() {
        String selecionado = (String) comboRegime.getSelectedItem();
        if ("Física".equals(selecionado)) {
            return Regime.PESSOA_FISICA;
        } else if ("Jurídica".equals(selecionado)) {
            return Regime.PESSOA_JURIDICA;
        }
        return null;
    }

    public JTextField[] getClienteJTextFields(){
        return new JTextField[]{
                textFieldId,
                textFieldNome,
                textFieldCpf,
                textFieldObsCLiente
        };
    }

    public JTextField[] getEnderecoJTextFields(){
        return new JTextField[]{
                textFieldIdEndereco,
                textFieldLogradouro,
                textFieldNumeroEndereco,
                textFieldBairro,
                textFieldObsEnderecos,
                textFieldCep,
                textFieldCidade,
                textFieldComplemento
        };
    }

    public JTextField[] getTelefoneJTextFields(){
        return new JTextField[]{
                textFieldIdTelefone,
                textFieldTelefone,
                textFieldContato
        };
    }

    public JTextField[] getTodosJTextFields(){
        return new JTextField[]{
                textFieldBairro,
                textFieldCep,
                textFieldCidade,
                textFieldComplemento,
                textFieldContato,
                textFieldCpf,
                textFieldId,
                textFieldLogradouro,
                textFieldNome,
                textFieldNumeroEndereco,
                textFieldObsCLiente,
                textFieldObsEnderecos,
                textFieldTelefone,
                textFieldIdEndereco,
                textFieldIdTelefone
        };
    }

    public JButton getBotaoAdicionarEndereco() {
        return botaoAdicionarEndereco;
    }

    public JButton getBotaoAdicionarTelefone() {
        return botaoAdicionarTelefone;
    }

    public JButton getBotaoBuscarCliente() {
        return botaoBuscarCliente;
    }

    public JButton getBotaoBuscarEndereco() {
        return botaoBuscarEndereco;
    }

    public JButton getBotaoBuscarTelefone() {
        return botaoBuscarTelefone;
    }

    public JButton getBotaoExcluirCliente() {
        return botaoExcluirCliente;
    }

    public JButton getBotaoExcluirEndereco() {
        return botaoExcluirEndereco;
    }

    public JButton getBotaoExcluirTelefone() {
        return botaoExcluirTelefone;
    }

    public JButton getBotaoLimparCampos() {
        return botaoLimparCampos;
    }

    public JButton getBotaoNovoCliente() {
        return botaoNovoCliente;
    }

    public JButton getBotaoSalvarCliente() {
        return botaoSalvarCliente;
    }

    public JButton getBotaoSalvarEndereco() {
        return botaoSalvarEndereco;
    }

    public JButton getBotaoSalvarTelefone() {
        return botaoSalvarTelefone;
    }

    public JButton getBotaoVoltar() {
        return botaoVoltar;
    }

    public JComboBox<String> getComboArea() {
        return comboArea;
    }

    public JComboBox<String> getComboRegime() {
        return comboRegime;
    }

    public JLabel getLabelArea() {
        return labelArea;
    }

    public JLabel getLabelBairro() {
        return labelBairro;
    }

    public JLabel getLabelCep() {
        return labelCep;
    }

    public JLabel getLabelCidade() {
        return labelCidade;
    }

    public JLabel getLabelComplemento() {
        return labelComplemento;
    }

    public JLabel getLabelContato() {
        return labelContato;
    }

    public JLabel getLabelCpf() {
        return labelCpf;
    }

    public JLabel getLabelId() {
        return labelId;
    }

    public JLabel getLabelIdEndereco() {
        return labelIdEndereco;
    }

    public JLabel getLabelIdTelefone() {
        return labelIdTelefone;
    }

    public JLabel getLabelListaClientes() {
        return labelListaClientes;
    }

    public JLabel getLabelListaEnderecos() {
        return labelListaEnderecos;
    }

    public JLabel getLabelListaTelefones() {
        return labelListaTelefones;
    }

    public JLabel getLabelLogradouro() {
        return labelLogradouro;
    }

    public JLabel getLabelNome() {
        return labelNome;
    }

    public JLabel getLabelNumeroEnderco() {
        return labelNumeroEnderco;
    }

    public JLabel getLabelObsClientes() {
        return labelObsClientes;
    }

    public JLabel getLabelObsEndereco() {
        return labelObsEndereco;
    }

    public JLabel getLabelPanelClientes() {
        return labelPanelClientes;
    }

    public JLabel getLabelPanelEnderecos() {
        return labelPanelEnderecos;
    }

    public JLabel getLabelPanelTelefones() {
        return labelPanelTelefones;
    }

    public JLabel getLabelRegime() {
        return labelRegime;
    }

    public JLabel getLabelStatusCliente() {
        return labelStatusCliente;
    }

    public JLabel getLabelTelefone() {
        return labelTelefone;
    }

    public JLabel getLabelTituloClientes() {
        return labelTituloClientes;
    }

    public JPanel getPanelBackground() {
        return panelBackground;
    }

    public JPanel getPanelClientes() {
        return panelClientes;
    }

    public JPanel getPanelEnderecos() {
        return panelEnderecos;
    }

    public JPanel getPanelTelefones() {
        return panelTelefones;
    }

    public JPanel getPaneltop() {
        return paneltop;
    }

    public JScrollPane getScrollPaneClientes() {
        return scrollPaneClientes;
    }

    public JScrollPane getScrollPaneEnderecos() {
        return scrollPaneEnderecos;
    }

    public JScrollPane getScrollPaneTelefones() {
        return scrollPaneTelefones;
    }

    public JTable getTableClientes() {
        return tableClientes;
    }

    public JTable getTableEnderecos() {
        return tableEnderecos;
    }

    public JTable getTableTelefones() {
        return tableTelefones;
    }

    public JTextField getTextFieldBairro() {
        return textFieldBairro;
    }

    public JTextField getTextFieldCep() {
        return textFieldCep;
    }

    public JTextField getTextFieldCidade() {
        return textFieldCidade;
    }

    public JTextField getTextFieldComplemento() {
        return textFieldComplemento;
    }

    public JTextField getTextFieldContato() {
        return textFieldContato;
    }

    public JTextField getTextFieldCpf() {
        return textFieldCpf;
    }

    public JTextField getTextFieldId() {
        return textFieldId;
    }

    public JTextField getTextFieldIdEndereco() {
        return textFieldIdEndereco;
    }

    public JTextField getTextFieldIdTelefone() {
        return textFieldIdTelefone;
    }

    public JTextField getTextFieldLogradouro() {
        return textFieldLogradouro;
    }

    public JTextField getTextFieldNome() {
        return textFieldNome;
    }

    public JTextField getTextFieldNumeroEndereco() {
        return textFieldNumeroEndereco;
    }

    public JTextField getTextFieldObsCLiente() {
        return textFieldObsCLiente;
    }

    public JTextField getTextFieldObsEnderecos() {
        return textFieldObsEnderecos;
    }

    public JTextField getTextFieldTelefone() {
        return textFieldTelefone;
    }
}
