package com.diskchop.view;


import com.formdev.flatlaf.FlatDarkLaf;

import javax.swing.*;

/**
 *
 * @author Yuri
 */
public class Estoque extends javax.swing.JDialog {

    /**
     * Creates new form CadastroProdutos
     */
    public Estoque(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        scrollTabela = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        panelBackground = new javax.swing.JPanel();
        panelTop = new javax.swing.JPanel();
        labelCategoria = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        botaoBuscar = new javax.swing.JButton();
        botaoVoltarTela = new javax.swing.JButton();
        botaoExportar = new javax.swing.JButton();
        panelMid = new javax.swing.JPanel();
        scrollPaneTabela = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        panelBot = new javax.swing.JPanel();
        labelFormulario = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        labelCategoriaProduto = new javax.swing.JLabel();
        comboProdutoCategoria = new javax.swing.JComboBox<>();
        labelQuantidade = new javax.swing.JLabel();
        textFieldQuantidade = new javax.swing.JTextField();
        labelPreco = new javax.swing.JLabel();
        textFieldPreco = new javax.swing.JTextField();
        Status = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        botaoSalvar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoNovoProduto = new javax.swing.JButton();

        scrollTabela.setBackground(new java.awt.Color(60, 60, 60));
        scrollTabela.setForeground(new java.awt.Color(250, 250, 250));

        tabela.setBackground(new java.awt.Color(60, 60, 60));
        tabela.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tabela.setForeground(new java.awt.Color(250, 250, 250));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        tabela.setSelectionBackground(new java.awt.Color(60, 60, 60));
        tabela.setSelectionForeground(new java.awt.Color(250, 250, 250));
        scrollTabela.setViewportView(tabela);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelTop.setBackground(new java.awt.Color(30, 30, 35));

        labelCategoria.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCategoria.setForeground(new java.awt.Color(255, 200, 87));
        labelCategoria.setText("Categoria:");

        comboCategoria.setBackground(new java.awt.Color(40, 40, 40));
        comboCategoria.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        comboCategoria.setForeground(new java.awt.Color(250, 250, 250));
        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maquina", "Barril", "Cilindro", "Mesa", "Cadeira" }));
        comboCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60)));
        comboCategoria.setMinimumSize(null);
        comboCategoria.setPreferredSize(null);

        botaoBuscar.setBackground(new java.awt.Color(15, 15, 20));
        botaoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/lupa.png"))); // NOI18N
        botaoBuscar.setToolTipText("Buscar");
        botaoBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60), 2));

        botaoVoltarTela.setBackground(new java.awt.Color(15, 15, 20));
        botaoVoltarTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/voltar.png"))); // NOI18N
        botaoVoltarTela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60), 2));

        botaoExportar.setBackground(new java.awt.Color(15, 15, 20));
       // botaoExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/diskchop/view/printer (1).png"))); // NOI18N
        botaoExportar.setToolTipText("Imprimir");
        botaoExportar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60), 2));

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
                panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTopLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(botaoVoltarTela)
                                .addGap(29, 29, 29)
                                .addComponent(labelCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoExportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(368, 368, 368))
        );
        panelTopLayout.setVerticalGroup(
                panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTopLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botaoBuscar)
                                        .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(botaoVoltarTela)
                                                .addGroup(panelTopLayout.createSequentialGroup()
                                                        .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(labelCategoria)
                                                                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(3, 3, 3)))
                                        .addComponent(botaoExportar))
                                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelMid.setBackground(new java.awt.Color(20, 20, 25));

        scrollPaneTabela.setBackground(new java.awt.Color(60, 60, 60));
        scrollPaneTabela.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N

        tabelaProdutos.setBackground(new java.awt.Color(60, 60, 60));
        tabelaProdutos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        tabelaProdutos.setForeground(new java.awt.Color(250, 250, 250));
        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null}
                },
                new String [] {
                        "ID", "NOME", "CATEGORIA", "QTDE", "PREÇO", "STATUS"
                }
        ));
        scrollPaneTabela.setViewportView(tabelaProdutos);

        javax.swing.GroupLayout panelMidLayout = new javax.swing.GroupLayout(panelMid);
        panelMid.setLayout(panelMidLayout);
        panelMidLayout.setHorizontalGroup(
                panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scrollPaneTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelMidLayout.setVerticalGroup(
                panelMidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMidLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(scrollPaneTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelBot.setBackground(new java.awt.Color(20, 20, 25));

        labelFormulario.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelFormulario.setForeground(new java.awt.Color(235, 235, 235));
        labelFormulario.setText("Estoque");

        labelNome.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(255, 200, 87));
        labelNome.setText("Nome:");

        textFieldNome.setBackground(new java.awt.Color(40, 40, 40));
        textFieldNome.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldNome.setForeground(new java.awt.Color(235, 235, 235));
        textFieldNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60)));
        textFieldNome.setMinimumSize(new java.awt.Dimension(64, 25));
        textFieldNome.setPreferredSize(new java.awt.Dimension(0, 25));
        textFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeActionPerformed(evt);
            }
        });

        labelCategoriaProduto.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCategoriaProduto.setForeground(new java.awt.Color(255, 200, 87));
        labelCategoriaProduto.setText("Categoria:");

        comboProdutoCategoria.setBackground(new java.awt.Color(40, 40, 40));
        comboProdutoCategoria.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        comboProdutoCategoria.setForeground(new java.awt.Color(250, 250, 250));
        comboProdutoCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maquina", "Barril", "Cilindro", "Mesa", "Cadeira" }));
        comboProdutoCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60)));
        comboProdutoCategoria.setMinimumSize(null);
        comboProdutoCategoria.setPreferredSize(new java.awt.Dimension(0, 25));

        labelQuantidade.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelQuantidade.setForeground(new java.awt.Color(255, 200, 87));
        labelQuantidade.setText("Quantidade:");

        textFieldQuantidade.setBackground(new java.awt.Color(40, 40, 40));
        textFieldQuantidade.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldQuantidade.setForeground(new java.awt.Color(250, 250, 250));
        textFieldQuantidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60)));
        textFieldQuantidade.setPreferredSize(new java.awt.Dimension(0, 25));

        labelPreco.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelPreco.setForeground(new java.awt.Color(255, 200, 87));
        labelPreco.setText("Preço:");

        textFieldPreco.setBackground(new java.awt.Color(40, 40, 40));
        textFieldPreco.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textFieldPreco.setForeground(new java.awt.Color(250, 250, 250));
        textFieldPreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60)));
        textFieldPreco.setPreferredSize(new java.awt.Dimension(0, 25));
        textFieldPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPrecoActionPerformed(evt);
            }
        });

        Status.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Status.setForeground(new java.awt.Color(255, 200, 87));
        Status.setText("Status:");

        comboStatus.setBackground(new java.awt.Color(40, 40, 40));
        comboStatus.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        comboStatus.setForeground(new java.awt.Color(250, 250, 250));
        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo", "Manutencao" }));
        comboStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60)));
        comboStatus.setMinimumSize(null);
        comboStatus.setPreferredSize(new java.awt.Dimension(0, 25));

        botaoSalvar.setBackground(new java.awt.Color(15, 15, 20));
        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/diskette.png"))); // NOI18N
        botaoSalvar.setToolTipText("Salvar");
        botaoSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60), 2));

        botaoCancelar.setBackground(new java.awt.Color(15, 15, 20));
        botaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/eraser.png"))); // NOI18N
        botaoCancelar.setToolTipText("Limpar");
        botaoCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60), 2));

        botaoExcluir.setBackground(new java.awt.Color(15, 15, 20));
        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/delete.png"))); // NOI18N
        botaoExcluir.setToolTipText("Deletar");
        botaoExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60), 2));

        botaoNovoProduto.setBackground(new java.awt.Color(15, 15, 20));
        botaoNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconesCrud/plus.png"))); // NOI18N
        botaoNovoProduto.setToolTipText("Novo Produto");
        botaoNovoProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60), 2));
        botaoNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotLayout = new javax.swing.GroupLayout(panelBot);
        panelBot.setLayout(panelBotLayout);
        panelBotLayout.setHorizontalGroup(
                panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBotLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBotLayout.createSequentialGroup()
                                                .addComponent(labelFormulario)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(panelBotLayout.createSequentialGroup()
                                                .addGroup(panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelBotLayout.createSequentialGroup()
                                                                .addGroup(panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(labelCategoriaProduto)
                                                                        .addComponent(labelQuantidade))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(comboProdutoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(textFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(panelBotLayout.createSequentialGroup()
                                                                .addComponent(Status)
                                                                .addGap(50, 50, 50)
                                                                .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(panelBotLayout.createSequentialGroup()
                                                                        .addComponent(labelPreco)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(textFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(panelBotLayout.createSequentialGroup()
                                                                        .addComponent(labelNome)
                                                                        .addGap(55, 55, 55)
                                                                        .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelBotLayout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addGroup(panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(botaoSalvar)
                                                                        .addComponent(botaoCancelar)))
                                                        .addGroup(panelBotLayout.createSequentialGroup()
                                                                .addComponent(botaoNovoProduto)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(botaoExcluir)))
                                                .addGap(129, 129, 129))))
        );
        panelBotLayout.setVerticalGroup(
                panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBotLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(labelFormulario)
                                .addGap(18, 18, 18)
                                .addGroup(panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBotLayout.createSequentialGroup()
                                                .addGroup(panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(labelNome)
                                                        .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(19, 19, 19)
                                                .addGroup(panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(labelCategoriaProduto)
                                                        .addComponent(comboProdutoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(19, 19, 19)
                                                .addGroup(panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(labelQuantidade)
                                                        .addComponent(textFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelPreco)
                                                        .addComponent(textFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Status)))
                                        .addGroup(panelBotLayout.createSequentialGroup()
                                                .addGroup(panelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(botaoNovoProduto)
                                                        .addComponent(botaoExcluir))
                                                .addGap(19, 19, 19)
                                                .addComponent(botaoSalvar)
                                                .addGap(18, 18, 18)
                                                .addComponent(botaoCancelar)))
                                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelBot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addComponent(panelMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void botaoNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textFieldPrecoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void textFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                UIManager.setLookAndFeel(new FlatDarkLaf());  // Para um tema escuro

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Estoque dialog = new Estoque(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel Status;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoExportar;
    private javax.swing.JButton botaoNovoProduto;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoVoltarTela;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboProdutoCategoria;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelCategoriaProduto;
    private javax.swing.JLabel labelFormulario;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBot;
    private javax.swing.JPanel panelMid;
    private javax.swing.JPanel panelTop;
    private javax.swing.JScrollPane scrollPaneTabela;
    private javax.swing.JScrollPane scrollTabela;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldPreco;
    private javax.swing.JTextField textFieldQuantidade;
    // End of variables declaration
}
